# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/moose/p_project/20170128_cggviewer/work/cgg-viewer-python/custom_frame.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ImageViewer import MyGraphicsView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 767)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hbox01 = QtWidgets.QHBoxLayout()
        self.hbox01.setObjectName("hbox01")
        self.lblPath = QtWidgets.QLabel(self.centralwidget)
        self.lblPath.setMinimumSize(QtCore.QSize(80, 0))
        self.lblPath.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblPath.setObjectName("lblPath")
        self.hbox01.addWidget(self.lblPath)
        self.edtPath = QtWidgets.QLineEdit(self.centralwidget)
        self.edtPath.setObjectName("edtPath")
        self.hbox01.addWidget(self.edtPath)
        self.btnOK = QtWidgets.QPushButton(self.centralwidget)
        self.btnOK.setObjectName("btnOK")
        self.hbox01.addWidget(self.btnOK)
        self.verticalLayout_2.addLayout(self.hbox01)
        self.hbox02 = QtWidgets.QHBoxLayout()
        self.hbox02.setObjectName("hbox02")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label.setObjectName("label")
        self.hbox02.addWidget(self.label)
        self.btnShowPalette = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowPalette.setObjectName("btnShowPalette")
        self.hbox02.addWidget(self.btnShowPalette)
        self.btnPrevPalette = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevPalette.setObjectName("btnPrevPalette")
        self.hbox02.addWidget(self.btnPrevPalette)
        self.edtPalette = QtWidgets.QLineEdit(self.centralwidget)
        self.edtPalette.setObjectName("edtPalette")
        self.hbox02.addWidget(self.edtPalette)
        self.btnNextPalette = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextPalette.setObjectName("btnNextPalette")
        self.hbox02.addWidget(self.btnNextPalette)
        self.verticalLayout_2.addLayout(self.hbox02)
        self.hbox03 = QtWidgets.QHBoxLayout()
        self.hbox03.setObjectName("hbox03")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_2.setObjectName("label_2")
        self.hbox03.addWidget(self.label_2)
        self.btnShowGraphics = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowGraphics.setObjectName("btnShowGraphics")
        self.hbox03.addWidget(self.btnShowGraphics)
        self.btnPrevGraphics = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevGraphics.setObjectName("btnPrevGraphics")
        self.hbox03.addWidget(self.btnPrevGraphics)
        self.edtGraphics = QtWidgets.QLineEdit(self.centralwidget)
        self.edtGraphics.setObjectName("edtGraphics")
        self.hbox03.addWidget(self.edtGraphics)
        self.btnNextGraphics = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextGraphics.setObjectName("btnNextGraphics")
        self.hbox03.addWidget(self.btnNextGraphics)
        self.verticalLayout_2.addLayout(self.hbox03)
        self.hbox04 = QtWidgets.QHBoxLayout()
        self.hbox04.setObjectName("hbox04")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setObjectName("label_5")
        self.hbox04.addWidget(self.label_5)
        self.btnShowMap = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowMap.setObjectName("btnShowMap")
        self.hbox04.addWidget(self.btnShowMap)
        self.btnPrevMap = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevMap.setObjectName("btnPrevMap")
        self.hbox04.addWidget(self.btnPrevMap)
        self.edtMap = QtWidgets.QLineEdit(self.centralwidget)
        self.edtMap.setObjectName("edtMap")
        self.hbox04.addWidget(self.edtMap)
        self.btnNextMap = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextMap.setObjectName("btnNextMap")
        self.hbox04.addWidget(self.btnNextMap)
        self.verticalLayout_2.addLayout(self.hbox04)
        self.hbox05 = QtWidgets.QHBoxLayout()
        self.hbox05.setObjectName("hbox05")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_6.setObjectName("label_6")
        self.hbox05.addWidget(self.label_6)
        self.btnShowAnimation = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowAnimation.setObjectName("btnShowAnimation")
        self.hbox05.addWidget(self.btnShowAnimation)
        self.btnPrevAnimation = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrevAnimation.setObjectName("btnPrevAnimation")
        self.hbox05.addWidget(self.btnPrevAnimation)
        self.edtAnimation = QtWidgets.QLineEdit(self.centralwidget)
        self.edtAnimation.setObjectName("edtAnimation")
        self.hbox05.addWidget(self.edtAnimation)
        self.btnNextAnimation = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextAnimation.setObjectName("btnNextAnimation")
        self.hbox05.addWidget(self.btnNextAnimation)
        self.verticalLayout_2.addLayout(self.hbox05)
        self.hlayoutMain = QtWidgets.QHBoxLayout()
        self.hlayoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlayoutMain.setObjectName("hlayoutMain")
        self.vboxControl = QtWidgets.QVBoxLayout()
        self.vboxControl.setObjectName("vboxControl")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vboxControl.addWidget(self.line_2)
        self.vbox01 = QtWidgets.QVBoxLayout()
        self.vbox01.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vbox01.setObjectName("vbox01")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.vbox01.addWidget(self.label_3)
        self.edtSummary = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.edtSummary.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.edtSummary.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.edtSummary.setReadOnly(True)
        self.edtSummary.setObjectName("edtSummary")
        self.vbox01.addWidget(self.edtSummary)
        self.vboxControl.addLayout(self.vbox01)
        self.hlayoutMain.addLayout(self.vboxControl)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hlayoutMain.addWidget(self.line)
        self.vboxPreview = QtWidgets.QVBoxLayout()
        self.vboxPreview.setObjectName("vboxPreview")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.vboxPreview.addWidget(self.label_4)

        #self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        #self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        #self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        #self.graphicsView.setObjectName("graphicsView")
        #self.vboxPreview.addWidget(self.graphicsView)

        self.graphicsScene = QtWidgets.QGraphicsScene()
        self.graphicsView = MyGraphicsView(self.graphicsScene)
        self.graphicsView.setObjectName("graphicsView")
        self.vboxPreview.addWidget(self.graphicsView)

        self.hlayout1 = QtWidgets.QHBoxLayout()
        self.hlayout1.setObjectName("hlayout1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout1.addItem(spacerItem)
        self.btnPrev = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrev.setObjectName("btnPrev")
        self.hlayout1.addWidget(self.btnPrev)
        self.edtIndex = QtWidgets.QLineEdit(self.centralwidget)
        self.edtIndex.setObjectName("edtIndex")
        self.hlayout1.addWidget(self.edtIndex)
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setObjectName("btnNext")
        self.hlayout1.addWidget(self.btnNext)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout1.addItem(spacerItem1)
        self.vboxPreview.addLayout(self.hlayout1)
        self.hlayoutMain.addLayout(self.vboxPreview)
        self.hlayoutMain.setStretch(0, 1)
        self.hlayoutMain.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.hlayoutMain)
        self.hlayout2 = QtWidgets.QHBoxLayout()
        self.hlayout2.setObjectName("hlayout2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.hlayout2.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayout2.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.hlayout2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.hlayout2.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.hlayout2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "魔力宝贝图档浏览器"))
        self.lblPath.setText(_translate("MainWindow", "数据根目录："))
        self.edtPath.setText(_translate("MainWindow", "test.jpg"))
        self.btnOK.setText(_translate("MainWindow", "扫描数据"))
        self.label.setText(_translate("MainWindow", "调色板："))
        self.btnShowPalette.setText(_translate("MainWindow", "显示"))
        self.btnPrevPalette.setText(_translate("MainWindow", "<<"))
        self.btnNextPalette.setText(_translate("MainWindow", ">>"))
        self.label_2.setText(_translate("MainWindow", "图档文件："))
        self.btnShowGraphics.setText(_translate("MainWindow", "显示"))
        self.btnPrevGraphics.setText(_translate("MainWindow", "<<"))
        self.btnNextGraphics.setText(_translate("MainWindow", ">>"))
        self.label_5.setText(_translate("MainWindow", "地图："))
        self.btnShowMap.setText(_translate("MainWindow", "显示"))
        self.btnPrevMap.setText(_translate("MainWindow", "<<"))
        self.btnNextMap.setText(_translate("MainWindow", ">>"))
        self.label_6.setText(_translate("MainWindow", "动画："))
        self.btnShowAnimation.setText(_translate("MainWindow", "显示"))
        self.btnPrevAnimation.setText(_translate("MainWindow", "<<"))
        self.btnNextAnimation.setText(_translate("MainWindow", ">>"))
        self.label_3.setText(_translate("MainWindow", "汇总信息"))
        self.label_4.setText(_translate("MainWindow", "显示"))
        self.btnPrev.setText(_translate("MainWindow", "<<"))
        self.btnNext.setText(_translate("MainWindow", ">>"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
